blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/cbeaulieu-gt/siege-web/issues/new?labels=question
    about: For questions (not bugs), open an Issue with the Question label. GitHub Discussions is not currently enabled on this repository.
