name: Claude

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  issues: write
  packages: read
  pull-requests: write

jobs:
  respond:
    uses: glitchwerks/github-actions/.github/workflows/claude-tag-respond.yml@89ade69f511f1b2634ea4bc2c7d4998dcbcfda50 # v2.6.1
    secrets: inherit
